#! /bin/sh

#$HOME/.config/lemonbar/render.sh | lemonbar -p -o '-5' -f 'KouzanBrushFont:size=10' -o '-1' -f 'Cica:size=18' -g 1920x24+0+0 | sh &
killall polybar
fcitx -rd &
feh --bg-fill $HOME/.config/feh/wallpaper.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &
export AWT_TOOLKIT=MToolkit

monitors=(`xrandr | grep "connected" | awk '{ print$1 }' | xargs`)

if [ ${#monitors[@]} -eq 1 ]; then
    bspc monitor ${monitors[0]} -d 壹 貳 參 肆 伍 陸 柒 捌 玖 拾
    polybar both &
else
    bspc monitor ${monitors[0]} -d 壹 貳 參 肆 伍
    bspc monitor ${monitors[1]} -d 陸 柒 捌 玖 拾
    polybar left &
    polybar right &
fi

bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton
